name: one_atta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  # State Management
  flutter_bloc: ^9.1.1
  # Routing
  go_router: ^16.2.0
  # Dependency Injection
  get_it: ^8.0.0
  # HTTP Client
  http: ^1.2.2
  dio: ^5.9.0
  # Functional Programming
  dartz: ^0.10.1
  # Local Storage
  shared_preferences: ^2.3.2
  # Equatable for easy comparisons
  equatable: ^2.0.7
  # svg image support
  flutter_svg: ^2.2.0
  # YouTube video player
  youtube_player_flutter: ^9.0.3
  material_design_icons_flutter: ^7.0.7296
  logger: ^2.6.1
  dotted_border: ^3.1.0
  #Share Plus
  share_plus: ^11.1.0
  rename_app: ^1.6.5
  percent_indicator: ^4.2.5
  sqflite: ^2.4.2
  path: ^1.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.13
  # Google Maps
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  intl: ^0.20.2
  video_player: ^2.10.0
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  # Payment Gateway
  razorpay_flutter: ^1.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/